apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discourse-dev
  namespace: discourse-dev
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discourse-dev-role-binding
  namespace: discourse-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discourse-dev
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: discourse-dev-codebuild
  namespace: discourse-dev
