apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discourse-developers-role-binding
  namespace: discourse-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discourse-dev
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: discourse-developers
  namespace: discourse-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discourse-developers-role-binding
  namespace: discourse-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discourse-stage
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: discourse-developers
  namespace: discourse-stage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discourse-developers-role-binding
  namespace: discourse-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discourse-prod
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: discourse-developers
  namespace: discourse-prod
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: discourse-developers
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: discourse-developers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: discourse-developers
subjects:
- kind: Group
  name: discourse-developers
  apiGroup: rbac.authorization.k8s.io
