apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discourse-prod
  namespace: discourse-prod
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discourse-prod-codebuild-role-binding
  namespace: discourse-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discourse-prod
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: discourse-prod-codebuild
  namespace: discourse-prod
