apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discourse-developers-role-binding
  namespace: discourse-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discourse-dev
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: discourse-developers
  namespace: discourse-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discourse-developers-role-binding
  namespace: discourse-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discourse-staging
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: discourse-developers
  namespace: discourse-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discourse-developers-role-binding
  namespace: discourse-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discourse-prod
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: discourse-developers
  namespace: discourse-prod
