apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discourse-stage
  namespace: discourse-stage
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - create
  - patch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discourse-stage-codebuild-role-binding
  namespace: discourse-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discourse-stage
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: discourse-stage-codebuild
  namespace: discourse-stage
